### ISSUE TITLE
✨ [Chore] Docker 개발 환경 구축

### ISSUE THREAD

**Issue by hyemch** [Matcha-Project/matcha#1]
## 📝 Description
- 동일한 환경에서 개발할 수 있도록 Docker 환경 구축하기

## ✅ To-do
- [x] docker compose 작성
- [x] client Dockerfile 작성
- [x] server Dockerfile 작성
- [x] nginx
- [x] DB 연결
